version: '3.9'

services:
  db:
    image: postgres:latest
    container_name: postgres
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: "qp-assessment"
      POSTGRES_USER: "qpAdmin"
      POSTGRES_PASSWORD: "Qp123"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: node_app
    ports:
      - "5000:5000"
    depends_on:
      - db
    environment:
      PORT: 5000
      DATABASE_URL: "postgres://qpAdmin:Qp123@postgres:5432/qp-assessment"

volumes:
  postgres_data:
